### ISSUE TITLE
HyBi connections violate protocol with certain headers in the opening handshake

### ISSUE THREAD

**Issue by Morfent** [faye/websocket-driver-node#24]
I was trying to debug some issues I was having with certain TCP connections on a SockJS server never closing after sockets had been destroyed. I used raw TCP connections to debug and found multiple issues with Faye's drivers when I was tinkering with the headers used in the opening handshakes:
- `Sec-WebSocket-Key` headers don't need to be included to establish a HyBi13 connection. According to the draft, this header is mandatory and the server should give a 404 response. Instead, the server just uses `''` or `undefined` as the `Sec-WebSocket-Key` value and creates the `Sec-WebSocket-Accept` value using it anyways
- Excluding `Sec-WebSocket-Version` headers while including `Sec-Websocket-Key` headers makes the server treat the connection as if it were using Hyxie75 as its protocol. This doesn't make sense, since Hyxie75 doesn't use `Sec-WebSocket-Key` headers at all.
- `Sec-WebSocket-Version` header values don't seem to make any impact on how the server handles the connection. Using `Sec-WebSocket-Version: 8` and including a `Sec-WebSocket-Origin` header doesn't make the server handle the origin the same way it does with `Origin` headers  and `Sec-WebSocket-Version: 13`.
- If the server only supports specific values of `Sec-WebSocket-Version`, the server should be sending a 404 response containing `Sec-WebSocket-Version` headers with the values the server does support if it supports HyBi13.

**Comment by jcoglan** [comment]
Could you take a look at the `request-validation` branch? I've made some changes there that should ensure that:

* `driver.http()` should not return a driver in cases where the headers are incomplete or invalid in the ways you mention
* `driver.isWebSocket()` should only return `true` in cases where no driver will be generated

What I'm not sure about is whether it would be desirable for `isWebSocket()` to return `true` in some cases where a driver cannot be constructed. For example, should a request with `Connection: Upgrade` and `Upgrade: websocket` be considered a WebSocket, even though no driver can be built for it? This is what Node considers an `upgrade` request.

If we did that, then the driver would need to generate a 404 response and emit something to tell you to close the socket. I figure it would be easier to have `isWebSocket()` return `false` and you send a 404 yourself.

**Comment by jcoglan** [comment]
What I'm worried about is this example in the docs:

```js
var http = require('http'),
    websocket = require('websocket-driver');

var server = http.createServer();

server.on('upgrade', function(request, socket, body) {
  if (!websocket.isWebSocket(request)) return;

  var driver = websocket.http(request);

  driver.io.write(body);
  socket.pipe(driver.io).pipe(socket);

  driver.messages.on('data', function(message) {
    console.log('Got a message', message);
  });

  driver.start();
});
```

Following this might account for TCP connections remaining open, since if `isWebSocket()` returns false here then the socket is never written to and may remain open. If people are following that usage there's not a lot I can do, since this module won't get a chance to close the socket, but I'd like to figure out something as ergonomic as possible to make sure the request is correctly handled.

**Comment by Morfent** [comment]
>Could you take a look at the request-validation branch?
[Made some changes](https://github.com/faye/websocket-driver-node/pull/25)

>Following this might account for TCP connections remaining open, since if isWebSocket() returns false here then the socket is never written to and may remain open. If people are following that usage there's not a lot I can do, since this module won't get a chance to close the socket, but I'd like to figure out something as ergonomic as possible to make sure the request is correctly handled.

Looking through Faye's dependents on npm, most are returning when `isWebSocket()` is false, but some aren't bothering to check before constructing the driver. If there's a way to handle writing the 400 response from the driver rather than from the packages depending on this, I think it might still be worth it

**Comment by jcoglan** [comment]
Hello again, I've revised my thinking on this a few times since first working on it, and my proposed changes are now on `master` (I can move them onto a topic branch if you'd rather).

My main concern is to make sure that it is as easy as possible for users to get the right behaviour, without having to add any addition stuff to their code, even if their code is not doing that checks it should be.

The interface Node provides as an entry point to using this library is the `upgrade` event:

```js
server.on('upgrade', (request, socket, body) => {
  // ...
})
```

As the user doesn't have a `response` object here, it's not obvious what to do if `isWebSocket()` returns false

```js
server.on('upgrade', (request, socket, body) => {
  if (!websocket.isWebSocket(request)) {
    let error = 'Not a WebSocket request'
    socket.write('HTTP/1.1 400 Bad Request\r\n')
    socket.write('Content-Type: text/plain\r\n')
    socket.write('Content-Length: ' + error.length + '\r\n')
    socket.write('\r\n')
    socket.write(error)
    socket.close()
  }
})
```

Even worse, what happens if they don't make this check at all:

```js
server.on('upgrade', (request, socket, body) => {
  let driver = websocket.http(request)
  socket.pipe(driver).pipe(socket)
  driver.start() // what if the request is invalid
})
```

In light of this, I'd like to keep `isWebSocket()` doing a minimum-viable check to see if the request looks like WebSocket, and leave more detailed validation to the individual drivers.

There is also the problem that some validation must be deferred until `start()` is called. For example, `Sec-WebSocket-Extensions` cannot be validated until the user has added the extentions they want:

```js
server.on('upgrade', (request, socket, body) => {
  if (websocket.isWebSocket(request)) {
    let driver = websocket.http(request)
    socket.pipe(driver).pipe(socket)
    driver.addExtension(deflate)
    driver.start() // only at this point can request headers be fully checked
  }
})
```

So, rather than build loads of version-specific validation into `isWebSocket()`, which would make it more complex and wouldn't work anyway, I've arranged things so that any driver can throw an error when constructing its handshake response, and the `start()` method will catch that and send a 400. `start()` will also check `isWebSocket()` itself to perform basic validation, in case the user didn't call that themselves.

On top of re-arranging validation responsibility, I've adjusted driver selection so that:

- If the request contains `sec-websocket-version` *or* `sec-websocket-key` you get Hybi
- otherwise, if the request contains `sec-websocket-key1` *or* `sec-websocket-key2` you get Draft76
- otherwise you get Draft75

i.e., we look for any signal the request is a Hybi request, otherwise fall back to older things. I've put in better checks for keys, and checked that the version is `13`.

Would you mind check these changes and giving me some feedback?

**Comment by Morfent** [comment]
This looks good

**Comment by jcoglan** [comment]
I'm closing this as it seems to handle the problem and I'm happy with the design. Thanks for all your feedback :)
