### ISSUE TITLE
How can I hookup an upgrade request as client?

### ISSUE THREAD

**Issue by rptl** [faye/websocket-driver-node#30]
I trying to hookup a  socket on http upgrade, but on client side, something like:

```
var req = https.request(options, (res) => { .. } )

req.on('upgrade', function upgrade(request, socket, body) {

     var driver = websocket.http(request);
     driver.io.pipe(socket)
     driver.messages.on('data', function(message) {
         console.log('Got a message', message);
     });
    driver.start()
})
```
I can see that webosocket-driver object has been created with readyState opened. But it does not keep opened. I should be missing something.

**Comment by jcoglan** [comment]
You can't use an HTTP client like this to make a WebSocket connection, as you need lower-level control over the underlying TCP/TLS connection and the construction of the request.

Instructions for using this library to build a client are here: https://github.com/faye/websocket-driver-node#client-side. If you're making a secure connection, use the `tls` rather than the `net` module.

If you want something higher level, you can use https://github.com/faye/faye-websocket-node which emulates the browser `WebSocket` interface and deals with all the underlying network logic for you.

**Comment by jcoglan** [comment]
Did this answer your question, @rptl? Can I close this issue?

**Comment by rptl** [comment]
Yes, please close it.
