### ISSUE TITLE
Version 0.7.2 is missing in yarn

### ISSUE THREAD

**Issue by Lonelind** [faye/websocket-driver-node#34]
Hi! It seems, last update (6 days ago from 19.06.2019) erased version 0.7.2 from yarn (at least, didn't look into npm registry yet).

![image](https://user-images.githubusercontent.com/1184404/59762847-d192eb00-92a0-11e9-8a9c-e75cf6c9122d.png)

We use 0.7.2 in our project, and simple `yarn` to update dependencies fails with 404

**Comment by jcoglan** [comment]
Version 0.7.2 was unpublished following #33, as you'll see from the [changelog](https://github.com/faye/websocket-driver-node/blob/master/CHANGELOG.md). You can also see from the [commit log](https://github.com/faye/websocket-driver-node/compare/0.7.2...0.7.3) that there is no functional difference between these releases.

**Comment by Lonelind** [comment]
Oh, I see, thank you!

**Comment by ressom** [comment]
Yeah ... no functional difference, but the ecosystem had dependencies on websocket-driver@0.7.2 and now 💩is broke.

It seems that the caching servers behind `registry.npmjs.org` are just now catching up to this unpublish event and we are getting 404s showing up during `npm install` ... a dev in Virginia is having the problem, but devs in North Dakota are not.  Additionally, our build servers in `us-east-1` are not able to get the .tgz anymore

In our use case we have `package-lock` in effect and for whatever reason it continues to resolve with are reference to 0.7.2

I think it's a waiting game until the NPM services get their stuff together and life goes back to normal.

**Comment by ressom** [comment]
... and just like that ... devs in North Dakota are now having the problem.  YAAAA CREEPING ERRORS!

**Comment by ressom** [comment]
Workaround in the meantime is to install websocket-driver@0.7.3 directly in our top-most package files ... even though runtime dep is great-grandchild (maybe even great-great-grand) 😞

**Comment by rnons** [comment]
I ended up editing yarn.lock manually

```
websocket-driver@>=0.5.1:
  version "0.7.3"
  resolved "https://registry.yarnpkg.com/websocket-driver/-/websocket-driver-0.7.3.tgz#a2d4e0d4f4f116f1e6297eba58b05d430100e9f9"
  integrity sha512-bpxWlvbbB459Mlipc5GBzzZwhoZgGEZLuqPaR0INBGnPAY1vdBX6hPnoFXiw+3yWxDuHyQjO2oXTMyS8A5haFg==
  dependencies:
    http-parser-js ">=0.4.0 <0.4.11"
    safe-buffer ">=5.1.0"
    websocket-extensions ">=0.1.1"
```

**Comment by Lonelind** [comment]
Not a good idea to edit lock file manually. It has a lot of information there, including checksums. It’d be more appropriate to run something like `npm I websocket-driver@0.7.3` to update both package and lock file.

**Comment by rnons** [comment]
I tried `yarn add websocket-driver@0.7.3`, but it doesn't work. Because `websocket-driver` is an indirect dependency of webpack-dev-server, the 0.7.2 version is still there.

When I said manually, I meant running `yarn add websocket-driver@0.7.3` in an empty folder, and copied the whole block including the checksum

**Comment by nickforddesign** [comment]
Yeah....... This is really frustrating. I am at a loss for what to do here, all of our projects that use webpack-dev-server are unable to deploy now.

I've tried deleting the lockfiles and updating, but all the parent packages are still pulling in 0.7.2.

Bout to ragequit for the day, this sucks.

```
└─┬ @vue/cli-service@3.8.4
  └─┬ webpack-dev-server@3.7.2
    ├─┬ sockjs@0.3.19
    │ └─┬ faye-websocket@0.10.0
    │   └── websocket-driver@0.7.2 
    └─┬ sockjs-client@1.3.0
      └─┬ faye-websocket@0.11.3
        └── websocket-driver@0.7.2

**Comment by stefanmaric** [comment]
Just dropping a line to say that this definitely broke some prod deploys. :smile: 

Some other people complaining: https://stackoverflow.com/questions/56718056/websocket-driver-was-not-found-on-deploy

**Comment by fabio-lab15** [comment]
I believe it's a bit irresponsible to simply remove a version from npm.
@jcoglan versioning exist for a purpose and unless something really grave happens (like malware infection) to a specific version, you should not remove them.
There are too many widely used packages that are dependent on this one.

**Comment by jcoglan** [comment]
Folks, as I mentioned above: 0.7.2 was unpublished because it was not a valid package: its `dependencies` data did not contain valid semver strings. We removed it following #33, and if it were left in the registry it would continue breaking people's builds.

0.7.3 was published after a few hours, contains identical source code, a valid package.json, and a patch number bump. It's the least disruptive action I could have taken here and upgrading to 0.7.3 should be without risk.

Rather than just leaving complaints here, I would appreciate if someone could find out how to upgrade a transitive dependency so that everyone can fix their build. Yes, unpublishing should be rare, but it does happen, and we should be able to deal with it.

**Comment by stefanmaric** [comment]
> Rather than just leaving complaints here, I would appreciate if someone could find out how to upgrade a transitive dependency so that everyone can fix their build. Yes, unpublishing should be rare, but it does happen, and we should be able to deal with it.

`npm i websocket-driver && npm rm websocket-driver` should be enough for most.

**Comment by nickforddesign** [comment]
@jcoglan sorry for not contributing constructively, I commented after a long, frustrating and fruitless day.

I was able to fix the issue in my projects, at first I assumed somewhere downstream, a package was requiring the missing version, but in fact this was not the case, the required version was not that specific. I think part of the problem was that the issue did not affect all of npm's servers at the same time, as I was unable to get 0.7.3 to install, even after deleting the lockfile, on my machine, or AWS.

However, my colleague jumped on a VPN and was able to get 0.7.3 to install, and we just copied the lockfile over as a temporary measure.

**Comment by turshija** [comment]
In our case `npm install` was failing with:
```
12262 verbose stack Error: 404 Not Found - GET https://registry.npmjs.org/websocket-driver/-/websocket-driver-0.7.2.tgz
```

quick fix was removing package-lock.json and letting npm install to generate a new one which bumped websocket-driver to 0.7.3

I also think that unpublishing a version is irresponsible no matter the reason (unless its infected by malware) since it creates issues that someone needs to debug and fix.

**Comment by jcoglan** [comment]
Hi folks, I really don't appreciate being called irresponsible for making a decision that's inconvenienced a few people for reasons I did not anticipate. To recap:

#33 alerted me to the fact that 0.7.2 contained dependencies that some build tools cannot process because they are not strictly valid semver expressions. My choice here was between these options:

- Leave 0.7.2 in the registry. Anyone who had it in their lockfile would keep it there, possibly indefinitely, and it would continue causing build failures just by existing
- Remove 0.7.2, causing a small fraction of this library's users some hassle

This module is installed over 5 million times per week. Having it indefinitely cause build failures would impose a substantial *ongoing* cost on affected users and on me responding to such issues.

Unpublishing this version does cause some hassle, but the number of people is small relative to my total user base -- npm only allows unpublishing within 24 hours, and this was unpublished much quicker than that. This hassle should not be ongoing, however, since the unpublish forces users to install another release.

What I did not anticipate is that some package managers make it unfeasably hard to upgrade transitive dependencies. I personally had not experienced this problem, and doing such upgrades is a very common requirement, so I expected it to not be any hassle to publish a new version with no functional changes in place of 0.7.2.

I was wrong about that, and for that I apologise, but I don't think it warrants insulting my judgement.

I'm keeping this thread open so that people can share helpful advice with those affected. Please do not abuse this by continuing to complain about things we can't change.

**Comment by turshija** [comment]
Thanks for clarification and please accept my apologies for calling you irresponsible.
Keep up the good work !

**Comment by jcoglan** [comment]
Thank you @turshija, I appreciate that :)

**Comment by rudym87** [comment]
A workaround for Yarn which does require editing `yarn.lock` but no tampering with versions or checksums, as suggested [here](https://github.com/yarnpkg/yarn/issues/4986#issuecomment-395036563):
1. Delete the entire `websocket-driver` entry from `yarn.lock`
2. Run `yarn` to generate a new lockfile

**Comment by AmanuenRaphim** [comment]
https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.8.3.tgz[[_**![image](https://user-images.githubusercontent.com/74922218/103474651-47678600-4d63-11eb-9e82-7df524bd5edb.jpeg)**_](https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.8.3.tgz)](https://registry.npmjs.org/@babel/code-frame/-/code-frame-7.8.3.tgz)
